# Generated by Chef for cms-deploy-test-lin.
# Local modifications will be overwritten.

# Grant privileges for debian-sys-main user
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY 'DOL_TpzaTDe9DLSqxkhv' WITH GRANT OPTION;

# Grant replication for a slave user.
GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%' identified by 'pb9yC9NJhvkxuAbA_L2L';

# remove remote access for root user and set password for local root user
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
UPDATE mysql.user SET Password=PASSWORD('qjhtLOiekxWz0BzpDEn0') WHERE User='root';

# Remove anonymous users
DELETE FROM mysql.user WHERE User='';

# Remove test database and access to it
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';

# Set the password for root@localhost
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('qjhtLOiekxWz0BzpDEn0');
